# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170801_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
