# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170801_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='UpVote_num',
            field=models.IntegerField(default=0),
        ),
    ]
